### ISSUE TITLE
publish cookbook to supermarket

### ISSUE THREAD

**Issue by vkhatri** [Icinga/chef-icingaweb2#5]
- Upload cookbook to Chef Supermarket
- Add Supermarket User vkhatri as a cookbook collaborator

**Comment by vkhatri** [comment]
@dnsmichi ping!

**Comment by dnsmichi** [comment]
Poke @bobapple please.

**Comment by vkhatri** [comment]
Also, please enable Travis CI.

**Comment by bobapple** [comment]
@vkhatri I uploaded the cookbook and added you as collaborator

TravisCI: https://travis-ci.org/Icinga/chef-icingaweb2

**Comment by vkhatri** [comment]
@bobapple 👍  

Thank you!
